# GET http://localhost:3000/api/users  


GET http://localhost:3000/api/users  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTViMmU5YWRkOTNhZTRmNzFlNjg5MWMiLCJlbWFpbCI6Im51cmllNDc3QGdtYWlsLmNvbSIsImlhdCI6MTYzMzUyODM4OCwiZXhwIjoxNjMzNTMxOTg4fQ.dYqTMt0Cj1iBDGxhLZc0SGRUd31BrCtFzxS7fMP2UUQ




###
GET http://localhost:3000/api/users/835
###

GET http://localhost:3000/api/users?kullanıcı=true



###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "isim":"keresdmas",
     "UserName":"keremsdsd331",
    "email":"nurie47assa7aasas@gmail.com",
     "password":"fensddsersdsd35as3"
    
   
}


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    
    "email":"nurie477@gmail.com",
     "password":"fener35.33"
   
}





# POST http://localhost:3000/api/users 



###
PATCH  http://localhost:3000/api/users/615895ecaa390ddce95a678c
Content-Type: application/json

{
    "isim":"kerim",
    "email":"messi_-_nurafddfssi@gmail.com",
    "password":"sddsdd"
}

###
PATCH  http://localhost:3000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVhYzVmZmM1ZmM3YzM2OTI0M2U2ZjgiLCJlbWFpbCI6ImdzX0BnbWFpay5jb20iLCJpYXQiOjE2MzMzNTM1MjMsImV4cCI6MTYzMzM1NzEyM30.sLdoSbqjdCZGB_G8xf6ZIy5Srou7Y5dPMzbyoihVN8A

{
    "isim":"hocalıdskerım"
}


###
GET http://localhost:3000/api/users/medelete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVhYzVmZmM1ZmM3YzM2OTI0M2U2ZjgiLCJlbWFpbCI6ImdzX0BnbWFpay5jb20iLCJpYXQiOjE2MzMzNTM1MjMsImV4cCI6MTYzMzM1NzEyM30.sLdoSbqjdCZGB_G8xf6ZIy5Srou7Y5dPMzbyoihVN8A

# ###
# DELETE http://localhost:3000/api/users/615356a49f697c316fdsd8a013


###
GET  http://localhost:3000/api/users/deleteAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTVhYzVmZmM1ZmM3YzM2OTI0M2U2ZjgiLCJlbWFpbCI6ImdzX0BnbWFpay5jb20iLCJpYXQiOjE2MzMzNDk4OTMsImV4cCI6MTYzMzM1MzQ5M30.-1ZS8_d3Y1QeLxWAIA4F4iJwSL7TUkxe_upeU8JWZmk


